apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
      - name: simple-api
        image: taylorbree/simple-api:latest
        ports:
        - containerPort: 8080
