apiVersion: v1
kind: Service
metadata:
  name: simple-api-service
  namespace: default
spec:
  selector:
    app: simple-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
