name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.SA_EMAIL }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  

  terraform:
    name: Provisioning Infrastructure
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: List Files
        run: ls -la terraform

      - name: Terraform Init
        working-directory: terraform
        run: terraform init
        
      - name: Get Access Token for Terraform
        id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.SA_EMAIL }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
    
      - name: Terraform Plan
        id: plan
        working-directory: terraform
        run: terraform plan -out=tfplan
        env: 
          GOOGLE_OAUTH_ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}
        
      - name: Apply Only If Changes Exist
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
        if: ${{ steps.plan.outputs.changes }} == 'true'
        env: 
          GOOGLE_OAUTH_ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
            context: .
            file: ./Dockerfile
            tags: ${{ secrets.DOCKER_USERNAME }}/simple-api:latest
            push: true

  Kubernetes-Workflow:
    name: Deploy the k8s workflow 
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      id-token: 'write'
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.SA_EMAIL }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials simple-api --zone us-central1-c --project ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Terraform Init
        working-directory: kubernetes_resource
        run: terraform init
        
      - name: Get Access Token for Terraform
        id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.SA_EMAIL }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}

      - name: Terraform Plan
        id: plan
        working-directory: kubernetes_resource
        run: terraform plan -out=tfplan
        env: 
          GOOGLE_OAUTH_ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}

      - name: Apply Only If Changes Exist
        working-directory: kubernetes_resource
        run: terraform apply -auto-approve tfplan
        if: ${{ steps.plan.outputs.changes }} == 'true'
        env: 
          GOOGLE_OAUTH_ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}

  verify:
    name: Verify Deployment
    runs-on: ubuntu-latest
    needs: Kubernetes-Workflow
    steps:
      - name: Test API Endpoint
        run: |
          sleep 60 # Give some time for the deployment to stabilize
          RESPONSE=$(curl --fail -s http://<API_ENDPOINT>/api)
          echo "Response: $RESPONSE"
